services:
  frontend:
    build:
      context: .
      dockerfile: docker/Dockerfile
      target: frontend
    ports:
      - "3000:3000"
    environment:
      - STRAPI_URL=http://backend:1337
    develop:
      watch:
        - path: ./frontend
          action: sync
          target: /prod/frontend
          ignore:
            - node_modules/
        - action: rebuild
          target: /prod/frontend
          path: ./frontend/package.json
    links:
      - backend
    depends_on:
      - backend

  backend:
    build:
      context: .
      dockerfile: docker/Dockerfile
      target: backend
    ports:
      - "1337:1337"
    env_file:
      - ./backend/.env
    develop:
      watch:
        - action: rebuild
          path: ./backend
          target: /prod/backend
          ignore:
            - .tmp/

    volumes:
      - ./backend/.tmp:/prod/backend/.tmp
