
name: 🦕 Build D4G Docusaurus website on Pull Request

on:
  # Triggers the workflow on Pull Request events but only for the default branch
  pull_request:
    branches:
      - master
    paths-ignore:
      - '.github/workflows/**'
      
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    name: Build Docusaurus
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies and build website
        run: |
          yarn install --frozen-lockfile
          yarn build

